### ISSUE TITLE
Enhancement request: Option to hide the "Favorite Contacts" list.

### ISSUE THREAD

**Issue by Ravenstencil** [qklabs/qksms-tracker#22]
When using the popup dialog to send a message the "Favorite Contacts" get in the way and it would be nice to be able to remove them from sight.

**Comment by srcreigh** [comment]
Sweet. I'm going to close this since I'm not 100% sure if we'll actually implement an option, but we will be thinking about the fact that it takes up a lot of space and try to fix it. Thanks @Ravenstencil.
