### ISSUE TITLE
Enhancement request: "Awesome extra features" isn't clearly defined.

### ISSUE THREAD

**Issue by Ravenstencil** [qklabs/qksms-tracker#24]
The QKSMS+ option in the menu displays the text "Unlock some awesome extra features!" but the only feature mentioned is "Automatic night mode". 

One feature doesn't count as "awesome extra features".

**Comment by srcreigh** [comment]
Well we've added per-contact notifications since then :-) so there are more than one haha.

**Comment by moezbhatti** [comment]
You're right, they should be better defined. Just FYI though, you also get custom responses for Android Wear and more theme colors
