### ISSUE TITLE
Enhancement Request: Add settings option to show/hide the "<Subject: No Subject>" text in MMS messages

### ISSUE THREAD

**Issue by erawhctim** [qklabs/qksms-tracker#26]
No MMS messages (group chats, pictures, audio files, etc) ever have a subject for me. It's always blank, and seeing the `<Subject: No Subject>` text is quite unsightly. 

A settings toggle to turn this off (or just removing it all together) would be fantastic!

**Comment by srcreigh** [comment]
This has been added since your issue was created. Thanks @erawhctim!
