### ISSUE TITLE
User in Play Store screenshots is simultaneously Moez and not Moez

### ISSUE THREAD

**Issue by The0x539** [qklabs/qksms-tracker#27]
As seen below, either the user is Moez and somehow/for some reason has a SMS conversation with himself, or the user is falsely claiming to be Moez in the conversation with Shane, or Shane is claiming that he is Moez and the user is Shane. If the first possibility was the intent as a joke, then fine, but still. ![lolwut](https://cloud.githubusercontent.com/assets/7350294/6361877/6024e4de-bc4c-11e4-811a-9db938a3f8ee.png)

**Comment by moezbhatti** [comment]
Haha, yeah there's a conversation with myself in there. Just reminding myself that QKSMS is awesome!

**Comment by The0x539** [comment]
Knew it!…?
