### ISSUE TITLE
If the phone number has a internationnal prefix number (+33 or +41)

### ISSUE THREAD

**Issue by Sicilia04** [qklabs/qksms-tracker#28]
The bug is if the phone number has a international prefix number (+33 or +41) the name and the picture doesn't appear the program say the number local. Exemple: +41 76 000 00 00 (number swiss) 076 000 00 00 ( local swiss number) same phone number but for the program it is two different number.

Sorry for my English, i'm French

**Comment by fcastilloec** [comment]
I'm not one of the developers but I'm trying to understand this better, so maybe we can help the developers understand the problem.
Is this contact saved in your phone as +41 76 ....... or do you have the contact saved as 076 ......?
When you received a text message, do you see the +41 or the 076 or both as conversations (how many conversations do you see for the same phone number)?
Does this also happens with the default SMS app, or is it just on QKSMS?
Also, knowing what type of phone and Android version might be useful.

**Comment by Sicilia04** [comment]
hello, 
yes it's a same issue
I had not seen before

**Comment by fcastilloec** [comment]
I guess that @srcreigh or @moezbhatti can mark this bug as closed then.

**Comment by Sicilia04** [comment]
i had close the issue
