### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by JayDoc386** [qklabs/qksms-tracker#34]
Notification sounds seem to be hit or miss when receiving a new SMS.  I am using the Nexus 6 Unlocked on Verizon Wireless.  I use to not get sound notifications when receiving MMS now it seems to work and SMS seems to not get it all the time when a new message arrives.

**Comment by fcastilloec** [comment]
I think you're issue might be the same as [Notifications automatically dissapear](https://github.com/qklabs/qksms-tracker/issues/3).

If this is so, the only way to always get notifications it's to leave QKSMS on the list-of-conversations screen (not in a specific contact conversation) and even remove it from the Recent app list on Android.

**Comment by srcreigh** [comment]
Closing because this is the same issue as #3. Thanks @JayDoc386 and @fcastilloec.
