### ISSUE TITLE
Pictures send horizontally

### ISSUE THREAD

**Issue by Yefssy** [qklabs/qksms-tracker#44]
Hey guys, the pictures I take send horizontally.  Is this normal, or a bug? This only happens with the pictures I've took.

**Comment by moezbhatti** [comment]
This should be something that was fixed in the last update. Can you give a reason for closing the issue?

**Comment by srcreigh** [comment]
@moezbhatti he may have seen that the issue is resolved :-)

**Comment by moezbhatti** [comment]
I know, I just want to clarify

**Comment by Yefssy** [comment]
I found out that the same thing happens with another app so it might not be a QKSMS bug. But it doesn't happen with my default messaging app. I'm confused.

**Comment by Yefssy** [comment]
Yeah, the bug is still there. I think it's a QKSMS bug.

**Comment by Yefssy** [comment]
Also another person made a post about this bug recently on Google+.

**Comment by Yefssy** [comment]
I don't have this issue anymore. It fixed when I updated the app to 1.4.5.
