### ISSUE TITLE
QKSMS Quick Contact Select Can't Find Contacts with a Number Listed as "Main"

### ISSUE THREAD

**Issue by arranf** [qklabs/qksms-tracker#47]
If you go to compose a message and attempt to find a contact by typing their name in the contact field it won't auto populate a contact if they only have a number listed as "Main"

**Comment by srcreigh** [comment]
Works for me. Do you have any extra details? Device model, Android OS version, etc?

**Comment by arranf** [comment]
Sure. Nexus 4, Android 5.1

Just to verify this contact had no "mobile" or "home" number listed just a
"main".
I'll try and reproduce now.

On 8 April 2015 at 13:09, Shane Creighton-Young <notifications@github.com>
wrote:

> Works for me. Do you have any extra details? Device model, Android OS
> version, etc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qklabs/qksms-tracker/issues/47#issuecomment-90893913>.
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by arranf** [comment]
Steps to reproduce:

Find a contact with just a single number listed
Change that number to "main"
Create a new message
Type in their name
Their name/number won't auto-complete

On 8 April 2015 at 13:11, Arran France <arran@hopecorby.org> wrote:

> Sure. Nexus 4, Android 5.1
>
> Just to verify this contact had no "mobile" or "home" number listed just a
> "main".
> I'll try and reproduce now.
>
> On 8 April 2015 at 13:09, Shane Creighton-Young <notifications@github.com>
> wrote:
>
>> Works for me. Do you have any extra details? Device model, Android OS
>> version, etc?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/qklabs/qksms-tracker/issues/47#issuecomment-90893913>
>> .
>>
>
>
>
> --
> *​​Arran France*
> ​​
> Communications, Youth Work, and Administration
> ​
> *​T.* 07425 159471​
>
> ​
> *​Hope Church Corby*
> Registered
> ​ UK​
>  Charity
> ​ ​
> 251549​
> *​*
> The Hope Centre
> 8 Princewood Road
> Corby
> NN17
> ​4
> AP
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by arranf** [comment]
@srcreigh I believe I can still reproduce this. Is there anything else I can do to help?

**Comment by moezbhatti** [comment]
Go into the general settings and make sure "Mobile numbers" is turned off
