### ISSUE TITLE
"This feature has not yet been implemented" when viewing thread details.

### ISSUE THREAD

**Issue by Wanyal** [qklabs/qksms-tracker#48]
I've tried to use this feature a number of times now, hoping to get various details about a message thread and get disappointed every time. Are there plans to implement whatever functionality was intended any time soon?

**Comment by moezbhatti** [comment]
Yeah, I think as soon as I'm done at my job I want to clean up all the little annoying things like this

**Comment by srcreigh** [comment]
@moezbhatti, wanna fix it tomorrow? :-D
