### ISSUE TITLE
Photos taken in Portrait mode are flipped sideways when sending as MMS

### ISSUE THREAD

**Issue by skadude66** [qklabs/qksms-tracker#5]
Repro steps

1. Take picture in portrait mode
2. Share picture with QKSMS (Share Picker)
3. Photo gets inserted sideways in QKSMS

**Comment by moezbhatti** [comment]
What device do you have?

**Comment by skadude66** [comment]
Samsung Galaxy Note 3. Stock rooted 4.4.2.

**Comment by mourningbell** [comment]
Also having this problem on Galaxy S4.

**Comment by Ravenstencil** [comment]
Same issue on ZTE Z995.

**Comment by srcreigh** [comment]
Pretty easy fix it seems. @moezbhatti Have a look here:

http://stackoverflow.com/questions/3647993/android-bitmaps-loaded-from-gallery-are-rotated-in-imageview

**Comment by srcreigh** [comment]
Just implemented a fix with the code. Will push a build tomorrow to the testing community so you guys can verify it. Thanks again for reporting @skadude66 @mourningbell @Ravenstencil.

**Comment by srcreigh** [comment]
https://github.com/recurser/exif-orientation-examples

**Comment by srcreigh** [comment]
Fixed!
