### ISSUE TITLE
Delivery confirmations not constant when texting an iPhone user

### ISSUE THREAD

**Issue by Yefssy** [qklabs/qksms-tracker#50]
DESCRIPTION
Delivery confirmations are not constant when texting an iPhone user. You will sometimes get delivery confirmations, but not all the time.

STEPS
1. Text a person who has an iPhone

EXPECTED
When texting an iPhone user you will be receiving constant delivery confirmations

REALITY
Not constant delivery confirmations when texting an iPhone user

**Comment by srcreigh** [comment]
1) Are you saying that sometimes delivery confirmations *never* arrive?
2) Do delivery confirmations work 100% of the time using other SMS apps?

**Comment by Yefssy** [comment]
They do arrive, but not all the time. And I think is not QKSMS only. It happens with other apps too.
