### ISSUE TITLE
Bad MMS message, missing 'ok' button

### ISSUE THREAD

**Issue by oscarmcm** [qklabs/qksms-tracker#54]
### DESCRIPTION
When you are a new user, this message appear, I just think that this is not a bug, it is a usability problem because the 'ok' button never exist.

### STEPS
1. Make a new instalation.
2. Don't setup the MMS config
3. Open the QKSMS app.

### EXPECTED
The message show 'ok' button

### REALITY
The message don't show 'ok' button

![screenshot_2015-04-05-09-05-16](https://cloud.githubusercontent.com/assets/2553459/7099373/75b80d28-dfae-11e4-965b-a21340ef91fb.png)

**Comment by moezbhatti** [comment]
This issue has been resolved for the next update :smile:

**Comment by oscarmcm** [comment]
Wuju :+1:  waiting for this
