### ISSUE TITLE
"Null" conversation after receiving an MMS

### ISSUE THREAD

**Issue by fcastilloec** [qklabs/qksms-tracker#7]
The February 12 update introduce another bug on MMS. Every time I received a picture, a new Null conversation is created.
Notifications are working great, but the subject bug is still present. Any text sent with a picture is repeated as the subject, which is annoying.

![15 - 1](https://cloud.githubusercontent.com/assets/1280530/6317548/8001c046-ba27-11e4-85f1-5b7c01619a03.png)

**Comment by srcreigh** [comment]
Thanks @fcastilloec. Working on this one today.

**Comment by srcreigh** [comment]
Fixed for next release @fcastilloec! Thanks.
