### ISSUE TITLE
MMS subject text shown

### ISSUE THREAD

**Issue by fcastilloec** [qklabs/qksms-tracker#8]
When sending or receiving an MMS together with text, QKSMS shows the text as both the message and the subject.
I'm attaching a picture that shows the problem with the text "Test" as both the body and Subject.
Subject should always be hidden.
![15 - 2](https://cloud.githubusercontent.com/assets/1280530/6317567/eaa88352-ba28-11e4-8c74-0c1b2d5dfe6f.png)

**Comment by srcreigh** [comment]
I don't think it should *always* be hidden. If someone sends you a text with a subject line that is different from the body, then you'll want to see the subject!

Definitely a bug in some cases though, i.e. subject and body are the same, or subject is empty. I'll talk to @moezbhatti about this and follow up later.

**Comment by srcreigh** [comment]
Moez and I are both working on this, we've split it up into a number of changes that should make MMS subject much better.

**Comment by fcastilloec** [comment]
I still think it's a bug because nobody uses the subject field in MMS. Nobody as in, no sms app out there (including the stock ones) use this field, and if this field could actually be edited by the user. Users don't know about it and don't use it, they simply send a message.
On top of this, QKSMS doesn't offer the option to input the subject and body of the message as separate fields, only body, so displaying both makes no sense. If you were to allow the user to add a subject and body, just so the MMS can be display the way they are now, will confused users and you'll hear complains, since no other SMS app out there allows this behavior making the duplicate subject field show all the time, unless the other user also used QKSMS to send the MMS.

**Comment by moezbhatti** [comment]
>Nobody as in, no sms app out there (including the stock ones) use this field, and if this field could actually be edited by the user.

Hangouts has support for it, tap and hold the send button to access the subject field IIRC

**Comment by srcreigh** [comment]
Fixed as of QKSMS 1.4.2.
