### ISSUE TITLE
Phone numbers with spaces recognized incorrectly

### ISSUE THREAD

**Issue by kpr2877** [qklabs/qksms-tracker#82]
Hello,
When you type a phone number in stock dialer, it is formatted to be more easy to read. For example: 123456789 is shown as 123 456 789.
The problem is, QKSMS thinks that space is added to put more numbers in one entry at phone book. Result: 123 as first receiver, 456 second receiver etc.
Full info here http://i.imgur.com/gw5Y7EA.png

**Comment by moezbhatti** [comment]
This has actually been fixed, I'll be posting an update either tonight or tomorrow night!

**Comment by moezbhatti** [comment]
When you get the update, leave a comment here and let me know to confirm that it fixed the problem for you, then we'll close the issue
